import assert from "node:assert/strict";
import { mkdtemp, rm, readFile } from "node:fs/promises";
import os from "node:os";
import path from "node:path";

async function main() {
  const root = await mkdtemp(path.join(os.tmpdir(), "kalender-exchange-workflows-test-"));
  process.env.KALENDER_DATA_DIR = root;
  process.env.KALENDER_MASTER_KEY = Buffer.alloc(32, 7).toString("base64");
  const originalFetch = globalThis.fetch;
  const { getDatabase } = await import("./database");
  const database = await getDatabase();
  try {
    const ews = await import("./exchange-calendar");
    const mail = await import("./exchange-mail");
    const transport = await import("./exchange-ews-client");
    const repository = await import("./calendar-account-repository");
    const events = await import("./calendar-repository");
    const service = await import("./calendar-event-service");
    const drafts = await import("./mail-draft-repository");
    const sync = await import("./exchange-draft-sync");
    const { parseMailDraftInput } = await import("./mail-draft-validation");
    const { checkExchangeCalendarChanges } = await import("./exchange-calendar-sync-state");
    const { parseCalendarEventInput } = await import("./calendar-validation");
    const { exchangeHtmlToContent } = await import("./exchange-rich-text");
    const { decodeNoteContent, noteContentToPlainText } = await import("../lib/note-content");
    const { renderMailHtml } = await import("./mail-rich-text");
    const credential = { kind: "exchange" as const, serverUrl: "https://mail.rwth-aachen.de/EWS/Exchange.asmx", username: "workflow@example.test", password: "mock-only" };
    const calls: Array<{ action: string; body: string }> = [];
    let reply: (action: string, body: string) => string | Response | Promise<string | Response> = () => { throw new Error("Unexpected EWS request"); };
    globalThis.fetch = (async (_url, init) => {
      const action = String(new Headers(init?.headers).get("SOAPAction")).split("/").pop()!;
      const body = String(init?.body);
      calls.push({ action, body });
      const response = await reply(action, body);
      return typeof response === "string" ? new Response(response) : response;
    }) as typeof fetch;
    const envelope = (content: string) => `<s:Envelope><s:Body><m:ResponseCode>NoError</m:ResponseCode>${content}</s:Body></s:Envelope>`;
    const calendarXml = (organizer = true) => envelope(`<t:CalendarItem><t:ItemId Id="meeting" ChangeKey="v2"/><t:UID>meeting-uid</t:UID><t:Subject>Meeting</t:Subject><t:Body BodyType="HTML">&lt;p&gt;&lt;b&gt;Hello&lt;/b&gt; &amp;amp; world&lt;/p&gt;</t:Body><t:Start>2026-09-10T08:00:00Z</t:Start><t:End>2026-09-10T09:00:00Z</t:End><t:ReminderIsSet>true</t:ReminderIsSet><t:ReminderMinutesBeforeStart>0</t:ReminderMinutesBeforeStart><t:IsMeeting>true</t:IsMeeting><t:IsOrganizer>${organizer}</t:IsOrganizer><t:MyResponseType>Accept</t:MyResponseType><t:LegacyFreeBusyStatus>OOF</t:LegacyFreeBusyStatus><t:OptionalAttendees><t:Attendee><t:Mailbox><t:EmailAddress>optional@example.test</t:EmailAddress></t:Mailbox><t:ResponseType>Tentative</t:ResponseType></t:Attendee></t:OptionalAttendees></t:CalendarItem>`);
    const parsed = ews.parseExchangeEventsResponse(calendarXml(), credential.serverUrl)[0]!;
    assert.equal(parsed.reminderMinutesBefore, 0);
    assert.equal(parsed.providerData?.reminderIsSet, true);
    assert.equal(parsed.availability, "oof");
    assert.equal(parsed.attendees[0]?.role, "optional");
    assert.equal(parsed.attendees[0]?.response, "Tentative");
    assert.equal(parsed.description, "Hello & world");
    assert.match(parsed.descriptionContent!, /"bold":true/);
    const rich = exchangeHtmlToContent('<script>alert(1)</script><p><b>bold</b> <i>italic</i><a href="javascript:bad">safe</a><a href="https://example.com">link</a></p>');
    assert(!rich.includes("javascript") && !rich.includes("alert(1)"));
    assert.match(await renderMailHtml(rich), /<strong/);
    assert.equal(decodeNoteContent(rich).length, 1);
    const account = await repository.saveExchangeCalendarAccount("Mock Exchange", credential);
    const calendarId = await repository.saveExchangeCalendar(account.id, { folderId: "calendar", name: "Calendar" }, credential.serverUrl, account.color);
    const input = parseCalendarEventInput({ calendarId, title: "Meeting", start: parsed.start, end: parsed.end, descriptionContent: rich, reminderMinutesBefore: 17, availability: "oof", attendees: [{ address: "optional@example.test", role: "optional" }], sendInvitations: true });
    assert.equal(input.reminderMinutesBefore, 17);
    reply = (action) => action === "GetItem" ? calendarXml() : envelope('<t:CalendarItem><t:ItemId Id="meeting" ChangeKey="v2"/></t:CalendarItem>');
    await ews.createExchangeCalendarEvent(credential, { folderId: "calendar", name: "Calendar" }, input);
    const create = calls.find((call) => call.action === "CreateItem")!.body;
    assert.match(create, /SendMeetingInvitations="SendToAllAndSaveCopy"/);
    assert.match(create, /BodyType="HTML"/);
    assert.match(create, /<t:ReminderMinutesBeforeStart>17</);
    assert.match(create, /<t:OptionalAttendees>/);
    assert(!create.includes("<t:RequiredAttendees>"));
    await ews.updateExchangeCalendarEvent(credential, { itemId: "meeting", changeKey: "v1" }, { ...input, attendees: [] });
    const update = calls.find((call) => call.action === "UpdateItem")!.body;
    assert.match(update, /NeverOverwrite/);
    assert.match(update, /SendMeetingInvitationsOrCancellations="SendToAllAndSaveCopy"/);
    assert.match(update, /<t:DeleteItemField><t:FieldURI FieldURI="calendar:OptionalAttendees"/);
    assert.match(update, /calendar:Resources/);
    await repository.saveExchangeCalendarEvents(calendarId, [parsed], "2026-09-01T00:00:00Z", "2026-10-01T00:00:00Z");
    let stored = (await events.listStoredCalendarEvents({ calendarIds: [calendarId], from: "2026-09-01T00:00:00Z", to: "2026-10-01T00:00:00Z" }))[0]!;
    const before = calls.length;
    await assert.rejects(() => service.upsertCalendarEvent({ ...input, id: stored.id, expectedUpdatedAt: stored.updatedAt, sendInvitations: false }), /确认/);
    assert.equal(calls.length, before, "notification consent is required before writing");
    await database.query("UPDATE calendar_events SET is_organizer=false WHERE id=$1", [stored.id]);
    await assert.rejects(() => service.upsertCalendarEvent({ ...input, id: stored.id, expectedUpdatedAt: stored.updatedAt }), /组织者/);
    reply = () => envelope("");
    for (const response of ["accept", "tentative", "decline"] as const) {
      stored = (await events.getStoredCalendarEvent(stored.id))!;
      await service.respondToCalendarMeeting(calendarId, stored.id, response, stored.updatedAt);
    }
    await ews.respondToExchangeMeeting(credential, { itemId: "meeting", changeKey: "v2" }, "cancel", "Cancelled");
    assert(calls.some((call) => call.body.includes("<t:AcceptItem>")));
    assert(calls.some((call) => call.body.includes("<t:TentativelyAcceptItem>")));
    assert(calls.some((call) => call.body.includes("<t:DeclineItem>")));
    assert.match(calls.at(-1)!.body, /ReferenceItemId[\s\S]*NewBodyContent/);
    reply = () => `<s:Envelope><m:FreeBusyResponseArray><t:FreeBusyResponse><m:ResponseMessage><m:ResponseCode>NoError</m:ResponseCode></m:ResponseMessage><t:FreeBusyView><t:MergedFreeBusy>0020</t:MergedFreeBusy></t:FreeBusyView></t:FreeBusyResponse><t:FreeBusyResponse><m:ResponseMessage><m:ResponseCode>ErrorMailRecipientNotFound</m:ResponseCode></m:ResponseMessage></t:FreeBusyResponse></m:FreeBusyResponseArray></s:Envelope>`;
    const availability = await ews.getExchangeAvailability(credential, ["one@example.test", "two@example.test"], parsed.start, parsed.end);
    assert.equal(availability[0]?.availability, "0020");
    assert.equal(availability[1]?.availability, "", "one inaccessible participant does not hide other results");

    let cursor = "cursor-1";
    let changed = true;
    reply = () => envelope(`<m:SyncState>${cursor}</m:SyncState><m:IncludesLastItemInRange>true</m:IncludesLastItemInRange><m:Changes>${changed ? '<t:Update><t:CalendarItem><t:ItemId Id="meeting"/></t:CalendarItem></t:Update>' : ''}</m:Changes>`);
    let delta = await checkExchangeCalendarChanges(credential, calendarId, "calendar", AbortSignal.timeout(5000));
    assert(delta.changed);
    assert.equal((await database.query("SELECT * FROM exchange_calendar_sync_state")).rows.length, 0, "cursor is not advanced before data commits");
    await delta.commit();
    changed = false; cursor = "cursor-2";
    delta = await checkExchangeCalendarChanges(credential, calendarId, "calendar", AbortSignal.timeout(5000));
    assert.equal(delta.changed, false, "idle calendar does not trigger a full scan");
    assert.match(calls.at(-1)!.body, /cursor-1/);
    let invalid = true;
    const healthyReply = reply;
    reply = (action, body) => { if (invalid) { invalid = false; return '<s:Envelope><m:ResponseCode>ErrorInvalidSyncStateData</m:ResponseCode></s:Envelope>'; } return healthyReply(action, body); };
    delta = await checkExchangeCalendarChanges(credential, calendarId, "calendar", AbortSignal.timeout(5000));
    assert(delta.changed);
    assert(!calls.at(-1)!.body.includes("<m:SyncState>"), "invalid cursor restarts from the server");
    const frames: string[] = [];
    reply = () => new Response(new ReadableStream({ start(controller) { const bytes = new TextEncoder().encode(envelope("<t:ModifiedEvent/>") + envelope("<t:CreatedEvent/>")); controller.enqueue(bytes.slice(0, 31)); controller.enqueue(bytes.slice(31)); controller.close(); } }));
    await transport.exchangeSoapRequest(credential, "GetStreamingEvents", "<m:GetStreamingEvents/>", undefined, (xml) => { frames.push(xml); });
    assert.equal(frames.length, 2);
    reply = () => new Response("<s:Envelope><broken>");
    await assert.rejects(() => transport.exchangeSoapRequest(credential, "GetStreamingEvents", "", undefined, () => {}), /中断/);

    const mailAccount = `exchange-mail:${account.id}`;
    const draft = await drafts.saveMailDraft(parseMailDraftInput({ accountId: mailAccount, to: ["one@example.test"], cc: ["two@example.test"], bcc: ["hidden@example.test"], subject: "Draft", textBody: "Local" }));
    let remoteKey = "mail-v1";
    let remoteSubject = "Remote";
    const remoteXml = () => envelope(`<t:Message><t:ItemId Id="mail-draft" ChangeKey="${remoteKey}"/><t:IsDraft>true</t:IsDraft><t:Subject>${remoteSubject}</t:Subject><t:Body BodyType="HTML">&lt;p&gt;&lt;b&gt;Remote body&lt;/b&gt;&lt;/p&gt;</t:Body><t:ToRecipients><t:Mailbox><t:EmailAddress>remote@example.test</t:EmailAddress></t:Mailbox></t:ToRecipients></t:Message>`);
    reply = (action) => action === "GetItem" ? remoteXml() : envelope(`<t:Message><t:ItemId Id="mail-draft" ChangeKey="${remoteKey}"/></t:Message>`);
    const saved = await sync.pushExchangeDraft(draft.id);
    assert.equal(saved?.itemId, "mail-draft");
    const mailCreate = calls.filter((call) => call.action === "CreateItem").at(-1)!.body;
    assert.match(mailCreate, /MessageDisposition="SaveOnly"/);
    assert.match(mailCreate, /<t:CcRecipients>/);
    assert.match(mailCreate, /hidden@example.test/);
    await drafts.saveMailDraft({ ...draft, subject: "Local changed" }, draft.id);
    remoteKey = "mail-v2";
    await assert.rejects(() => sync.pushExchangeDraft(draft.id), /保留哪一版/);
    await sync.pullExchangeDraft(mailAccount, mail.parseExchangeMessages(remoteXml())[0]!);
    assert.equal((await drafts.getMailDraft(draft.id))?.subject, "Local changed", "simultaneous remote change preserves dirty local draft");
    await sync.pullExchangeDraft(mailAccount, mail.parseExchangeMessages(remoteXml())[0]!, true);
    let imported = (await drafts.getMailDraft(draft.id))!;
    assert.equal(imported.subject, "Remote");
    assert.equal(noteContentToPlainText(imported.bodyContent), "Remote body");
    remoteKey = "mail-v3"; remoteSubject = "Do not lose local edits";
    const attachment = { id: "att", filename: "notes.txt", contentType: "text/plain", sizeBytes: 4, inline: false };
    const remoteWithFile = { ...mail.parseExchangeMessages(remoteXml())[0]!, attachments: [attachment] };
    reply = async (action) => {
      if (action === "GetAttachment") {
        await drafts.saveMailDraft({ ...imported, subject: "Edited during download" }, draft.id);
        return envelope('<t:FileAttachment><t:Name>notes.txt</t:Name><t:ContentType>text/plain</t:ContentType><t:Content>dGVzdA==</t:Content></t:FileAttachment>');
      }
      return remoteXml();
    };
    await assert.rejects(() => sync.pullExchangeDraft(mailAccount, remoteWithFile, true), /同步期间/);
    assert.equal((await drafts.getMailDraft(draft.id))?.subject, "Edited during download");
    reply = () => envelope('<t:FileAttachment><t:Name>notes.txt</t:Name><t:ContentType>text/plain</t:ContentType><t:Content>dGVzdA==</t:Content></t:FileAttachment>');
    await sync.pullExchangeDraft(mailAccount, remoteWithFile, true);
    imported = (await drafts.getMailDraft(draft.id))!;
    assert.equal(imported.attachments.length, 1);
    const { mailDraftAttachmentPath } = await import("./mail-draft-attachment-service");
    assert.equal(await readFile(mailDraftAttachmentPath((await drafts.listMailDraftAttachmentRecords(draft.id))[0]!), "utf8"), "test");
    reply = () => envelope('<t:ItemAttachment><t:Name>original</t:Name><t:Message><t:MimeContent>U3ViamVjdDogVGVzdA0KDQpCb2R5</t:MimeContent></t:Message></t:ItemAttachment>');
    const eml = await mail.getExchangeAttachment(credential, "nested");
    assert.equal(eml.filename, "original.eml");
    assert.equal(eml.contentType, "message/rfc822");
    assert.match(Buffer.from(eml.content).toString(), /Subject: Test/);
    await drafts.saveMailDraft({ ...imported, subject: "Keep unsent work" }, draft.id);
    await sync.synchronizeExchangeDrafts(mailAccount, [], ["mail-draft"]);
    assert.equal((await drafts.getMailDraft(draft.id))?.subject, "Keep unsent work");

    // Simulate a server commit whose HTTP response never reaches us.
    const uncertain = await drafts.saveMailDraft(parseMailDraftInput({ accountId: mailAccount, to: ["one@example.test"], subject: "Lost create response", textBody: "Keep local" }));
    const uncertaintyStart = calls.length;
    reply = (action, body) => {
      assert.equal(action, "CreateItem");
      assert.match(body, /PropertyName="DaylineDraftId"/);
      assert(body.includes(uncertain.id));
      throw new TypeError("connection closed after commit");
    };
    await assert.rejects(() => sync.pushExchangeDraft(uncertain.id));
    assert.equal((await database.query("SELECT * FROM exchange_draft_creates WHERE draft_id=$1", [uncertain.id])).rows.length, 1);
    reply = () => new Response("", { status: 401 });
    await assert.rejects(() => sync.pushExchangeDraft(uncertain.id));
    assert.equal((await database.query("SELECT * FROM exchange_draft_creates WHERE draft_id=$1", [uncertain.id])).rows.length, 1, "failed recovery authentication must not erase an uncertain create");
    reply = (action) => { assert.equal(action, "FindItem"); return envelope(""); };
    await assert.rejects(() => sync.pushExchangeDraft(uncertain.id), /不会重复创建/);
    const recoveredXml = () => envelope(`<t:Message><t:ItemId Id="recovered-draft" ChangeKey="recovered-v1"/><t:IsDraft>true</t:IsDraft><t:ExtendedProperty><t:ExtendedFieldURI PropertySetId="d672a86d-8b6b-4b4d-9ca8-0bc9fe919f63" PropertyName="DaylineDraftId" PropertyType="String"/><t:Value>${uncertain.id}</t:Value></t:ExtendedProperty><t:Subject>Remote recovered</t:Subject></t:Message>`);
    reply = () => recoveredXml();
    await assert.rejects(() => sync.pushExchangeDraft(uncertain.id), /保留本地或 Exchange/);
    await assert.rejects(() => sync.pushExchangeDraft(uncertain.id), /保留本地或 Exchange/, "repeated sync still requires conflict resolution");
    assert.equal(mail.parseExchangeMessages(recoveredXml())[0]?.localDraftId, uncertain.id);
    await sync.pushExchangeDraft(uncertain.id, true);
    assert.equal(calls.slice(uncertaintyStart).filter((call) => call.action === "CreateItem").length, 1, "response loss followed by recovery never creates a second remote draft");
    assert(calls.slice(uncertaintyStart).some((call) => call.action === "UpdateItem" && call.body.includes("recovered-draft")));
    assert.equal((await drafts.getMailDraft(uncertain.id))?.subject, "Lost create response");

    const outgoingStart = calls.length;
    reply = (action) => action === "GetItem" ? envelope('<t:Message><t:InternetMessageId>&lt;original@example.test&gt;</t:InternetMessageId></t:Message>') : action === "CreateAttachment" ? envelope('<t:FileAttachment><t:AttachmentId Id="uploaded" RootItemId="outgoing" RootItemChangeKey="with-attachment"/></t:FileAttachment>') : envelope('<t:Message><t:ItemId Id="outgoing" ChangeKey="initial"/></t:Message>');
    await mail.sendExchangeMessage(credential, { to: ["sender@example.test", "other@example.test"], cc: ["copy@example.test"], bcc: [], subject: "Reply all", textBody: "Reply", replyToItemId: "original", attachments: [{ filename: "forwarded.txt", contentType: "text/plain", content: new TextEncoder().encode("original bytes") }] });
    const outgoing = calls.slice(outgoingStart);
    const outgoingBody = outgoing.find((call) => call.action === "CreateItem")!.body;
    assert.match(outgoingBody, /sender@example.test/);
    assert.match(outgoingBody, /other@example.test/);
    assert.match(outgoingBody, /copy@example.test/);
    assert(outgoingBody.indexOf("<t:InReplyTo>") < outgoingBody.indexOf("<t:ToRecipients>"));
    assert(outgoingBody.indexOf("<t:References>") > outgoingBody.indexOf("<t:CcRecipients>"));
    assert.match(outgoing.find((call) => call.action === "CreateAttachment")!.body, new RegExp(Buffer.from("original bytes").toString("base64")));
    assert.match(outgoing.find((call) => call.action === "SendItem")!.body, /ChangeKey="with-attachment"/);

    const { createInitialAdmin, runWithMcpActor } = await import("./auth");
    const actor = await createInitialAdmin({ displayName: "Workflow test", username: "workflow-test", password: "test-password-1234" });
    const { runCalendarOperation } = await import("./calendar-operation");
    await runWithMcpActor(actor, async () => {
      let writes = 0;
      const request = (body = '{"title":"one"}') => new Request("http://localhost/api/calendar-events", { method: "POST", headers: { "x-calendar-operation-id": "workflow-operation-1" }, body });
      const operation = async () => { writes++; return Response.json({ ok: true }, { status: 201 }); };
      assert.equal((await runCalendarOperation(request(), operation)).status, 201);
      assert.equal((await runCalendarOperation(request(), operation)).status, 201);
      assert.equal(writes, 1, "replaying an offline operation does not resend invitations");
      const retryRequest = (id: string) => new Request("http://localhost/api/calendar-events", { method: "POST", headers: { "x-calendar-operation-id": id }, body: '{"title":"retry"}' });
      let conflict = true;
      let retryWrites = 0;
      const retryOperation = async (beginWrite: () => Promise<void>) => {
        if (conflict) return Response.json({ conflicts: [{ id: "occupied" }] }, { status: 409 });
        await beginWrite();
        retryWrites++;
        return Response.json({ ok: true }, { status: 201 });
      };
      assert.equal((await runCalendarOperation(retryRequest("resolved-conflict"), retryOperation)).status, 409);
      conflict = false;
      const retries = await Promise.all([runCalendarOperation(retryRequest("resolved-conflict"), retryOperation), runCalendarOperation(retryRequest("resolved-conflict"), retryOperation)]);
      assert(retries.some((response) => response.status === 201));
      assert.equal((await runCalendarOperation(retryRequest("resolved-conflict"), retryOperation)).status, 201);
      assert.equal(retryWrites, 1, "a resolved preflight conflict can retry, even with concurrent retries, without duplicate writes");
      let uncertainWrites = 0;
      const uncertainOperation = async (beginWrite: () => Promise<void>) => { await beginWrite(); uncertainWrites++; return Response.json({ message: "lost response" }, { status: 502 }); };
      assert.equal((await runCalendarOperation(retryRequest("uncertain-write"), uncertainOperation)).status, 502);
      assert.equal((await runCalendarOperation(retryRequest("uncertain-write"), uncertainOperation)).status, 502);
      assert.equal(uncertainWrites, 1, "unknown remote outcomes remain protected from replay");
      assert.equal((await runCalendarOperation(request('{"title":"two"}'), operation)).status, 409);
    });
    console.log("Exchange workflows passed: meeting consent/responses, fields, cursor recovery, streamed notifications, draft conflict/file atomicity, nested attachment and replay deduplication");
  } finally {
    globalThis.fetch = originalFetch;
    await database.close();
    await rm(root, { recursive: true, force: true });
  }
}
main().catch((error) => { console.error(error); process.exitCode = 1; });
